stages:
  - deploy

variables:
  AWS_REGION: "us-east-2"
  VAULT_SERVER_URL: "http://18.217.65.225:8200"
  VAULT_AUTH_ROLE: "demo"
  VAULT_AUTH_PATH: "gitlab"
  VAULT_NAMESPACE: "/"

deploy:
  when: manual
  stage: deploy
  image: alpine:3

  id_tokens:
    VAULT_ID_TOKEN:
      aud: "http://18.217.65.225"

  secrets:
    API_KEY:
      file: false
      vault: prod/example/apikey@kv # vault kv get -field=apikey kv/prod/example

    AWS:
      file: false
      vault: # vault read -field=data aws/sts/deploy
        engine:
          name: generic
          path: aws
        path: sts/deploy
        field: data

  before_script:
    - apk add jq aws-cli > /dev/null

  script:
    # Manual
    - export VAULT_TOKEN=$(vault write -field=token auth/gitlab/login role=example jwt=$VAULT_ID_TOKEN)
    - export API_KEY=$(vault kv get -field=apikey kv/prod/example)
    - export AWS=$(vault read -field=data aws/sts/deploy)

    - env | grep API_KEY
    - env | grep AWS

    - export AWS_ACCESS_KEY_ID=$(jq -r .access_key <<< $AWS)
    - export AWS_SECRET_ACCESS_KEY=$(jq -r .secret_key <<< $AWS)
    - export AWS_SESSION_TOKEN=$(jq -r .session_token <<< $AWS)

    - env | grep AWS_

    - aws sts get-caller-identity

    - 'curl -sH "Authorization: Basic $API_KEY" https://api.fda.gov/food/enforcement.json | jq .results'
