stages:
  - deploy

variables:
  AWS_REGION: "us-east-2"
  VAULT_ADDR: "http://vault.example.com:8200"
  VAULT_AUTH_PATH: "gitlab"
  VAULT_AUTH_ROLE: "demo"

deploy:
  when: manual
  stage: deploy
  image: alpine:3

  id_tokens:
    VAULT_JWT:
      aud: "https://vault.example.com"

  before_script:
    - echo "Starting `before_script`..."

    # install jq, aws, curl
    - apk add jq aws-cli curl > /dev/null 2>&1

    # install vault
    - wget https://releases.hashicorp.com/vault/1.16.3/vault_1.16.3_linux_amd64.zip > /dev/null 2>&1
    - unzip vault_1.16.3_linux_amd64.zip vault -d /usr/local/bin/ > /dev/null 2>&1

    # create alias for output
    - alias mask="sed -E 's/[0-9]{12}/************/g'"

  script:
    - echo "Starting `script`..."

    # login to Vault
    - export VAULT_TOKEN=$(vault write -field=token auth/$VAULT_AUTH_PATH/login role=$VAULT_AUTH_ROLE jwt=$VAULT_JWT)

    # pull secrets
    - export API_KEY="$(vault kv get -field=apikey kv/prod/example)"
    - export AWS_CREDS="$(vault read -format=json -field=data aws/sts/deploy)"

    # use secrets
    - export AWS_ACCESS_KEY_ID=$(echo $AWS_CREDS | jq -r .access_key)
    - export AWS_SECRET_ACCESS_KEY=$(echo $AWS_CREDS | jq -r .secret_key)
    - export AWS_SESSION_TOKEN=$(echo $AWS_CREDS | jq -r .session_token)

    - aws sts get-caller-identity | mask
    - 'curl -sH "Authorization: Basic $API_KEY" https://api.fda.gov/food/enforcement.json | jq .results'
