stages:
  - deploy

variables:
  AWS_REGION: "us-east-2"
  VAULT_SERVER_URL: "https://vault.example.com"
  VAULT_AUTH_ROLE: "demo"
  VAULT_AUTH_PATH: "gitlab"
  VAULT_NAMESPACE: "/"

deploy:
  stage: deploy
  image: alpine:3

  id_tokens:
    VAULT_ID_TOKEN:
      aud: https://example.vault.com

  secrets:
    # vault kv get -field=apikey kv/prod/example
    API_KEY:
      file: false
      vault: prod/example/apikey@kv

    # vault read -field=data aws/sts/deploy
    AWS:
      file: false
      vault:
        engine:
          name: generic
          path: aws
        path: sts/deploy
        field: data

  before_script:
    - apk add jq aws-cli > /dev/null

  script:
    - >
      env | grep API_KEY || true
      env | grep API_KEY || true

      export AWS_ACCESS_KEY_ID=$(jq -r .access_key <<< $AWS)
      export AWS_SECRET_ACCESS_KEY=$(jq -r .secret_key <<< $AWS)
      export AWS_SESSION_TOKEN=$(jq -r .session_token <<< $AWS)

      env | grep AWS_

      aws sts get-caller-identity

      curl -sH "Authorization: Basic $API_KEY" https://api.fda.gov/food/enforcement.json | jq .results
