stages:
  - deploy

variables:
  AWS_REGION: "us-east-2"
  VAULT_ADDR: "http://18.217.65.225:8200"
  VAULT_AUTH_ROLE: "demo"
  VAULT_AUTH_PATH: "gitlab"
  # VAULT_NAMESPACE: "/"

deploy:
  when: manual
  stage: deploy
  image: alpine:3

  id_tokens:
    VAULT_ID_TOKEN:
      aud: "https://vault.example.com"

  before_script:
    - apk add jq aws-cli > /dev/null 2>&1
    - wget https://releases.hashicorp.com/vault/1.16.3/vault_1.16.3_linux_amd64.zip > /dev/null 2>&1
    - unzip vault_1.16.3_linux_amd64.zip vault -d /usr/local/bin/ > /dev/null 2>&1

  script:
    - export VAULT_TOKEN=$(vault write -field=token auth/$VAULT_AUTH_PATH/login role=$VAULT_AUTH_ROLE jwt=$VAULT_ID_TOKEN)
    - export API_KEY=$(vault kv get -field=apikey kv/prod/example)
    - export AWS_CREDS=$(vault read -format=json -field=data aws/sts/deploy)

    - env | grep API_KEY
    - env | grep AWS_CREDS

    - export AWS_ACCESS_KEY_ID=$(jq -r .access_key <<< $AWS_CREDS)
    - export AWS_SECRET_ACCESS_KEY=$(jq -r .secret_key <<< $AWS_CREDS)
    - export AWS_SESSION_TOKEN=$(jq -r .session_token <<< $AWS_CREDS)

    - env | grep AWS_

    - aws sts get-caller-identity

    - 'curl -sH "Authorization: Basic $API_KEY" https://api.fda.gov/food/enforcement.json | jq .results'
